# Линейная алгебра
# GeekBrains
## ДЗ Урока 2
## Виталий Казанцев

__Часть 1__

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    

__а)__ Операция невозможна, т.к.  число столбцов матрицы $A$ неравно числу строк матрицы $B$  
__б)__ Число столбцов матрицы $A$ равно числу строк матрицы $B$ и равно пяти, следовательно операция $A\cdot B$ возможна. Результатом будет матрица размерностью $2\times3$  
__в)__ Число столбцов матрицы $A$ равно числу строк матрицы $B$ и равно трём, следовательно операция $A\cdot B$ возможна. Результатом будет матрица размерностью $8\times8$  
__г)__ Матрицы $A и B$ квадратные размерность четыре, операция умножения возможно, результатом будет матрица $4\times4$  

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$



__Решение:__
### $A+B=\begin{pmatrix}1&-2 \\ 3&0\end{pmatrix}+\begin{pmatrix}4&-1 \\ 0&5\end{pmatrix}=\begin{pmatrix} 5&-3 \\ 3&5\end{pmatrix}$  
### $A\cdot B=\begin{pmatrix}1&-2 \\ 3&0\end{pmatrix}\cdot\begin{pmatrix}4&-1 \\ 0&5\end{pmatrix}=\begin{pmatrix}1\cdot4+(-2)\cdot0 \\ 3\cdot4+0\cdot0\end{pmatrix}  \begin{pmatrix}1\cdot(-1)+(-2)\cdot5 \\ 3\cdot(-1)+0\cdot5\end{pmatrix}=\begin{pmatrix}4&-11 \\ 12&-3\end{pmatrix}$

In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, -2],
    [3, 0]
])
B = np.array([
    [4, -1],
    [0, 5]
])
print(A + B)
print(np.dot(A, B))

[[ 5 -3]
 [ 3  5]]
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    


__Решение:__
### $3A-2B+4C=3\cdot\begin{pmatrix}1&7\\3&-6\end{pmatrix}-2\begin{pmatrix}0&5\\2&-1\end{pmatrix}+4\begin{pmatrix}2&-4\\1&1\end{pmatrix}=\begin{pmatrix}3&21\\9&-18\end{pmatrix}+\begin{pmatrix}0&-10\\-4&2\end{pmatrix}+\begin{pmatrix}8&-16\\4&4\end{pmatrix}=\begin{pmatrix}11&-5\\9&-12\end{pmatrix}$

In [3]:
A = np.array([
    [1, 7],
    [3, -6]
])
B = np.array([
    [0, 5],
    [2, -1]
])
C = np.array([
    [2, -4],
    [1, 1]
])

3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.



__Решение:__  
__а)__  
  
### $\begin{pmatrix}4&1\\5&-2\\2&3\end{pmatrix}\cdot\begin{pmatrix}4&5&2\\1&-2&3\end{pmatrix}=\begin{pmatrix}4\cdot4+1\cdot1&4\cdot5+1\cdot(-2)&4\cdot2+1\cdot3\\5\cdot4+(-2)\cdot1&5\cdot5+(-2)\cdot(-2)&5\cdot2+(-2)\cdot3\\2\cdot4+3\cdot1&2\cdot5+3\cdot(-2)&2\cdot2+3\cdot3\end{pmatrix}=\begin{pmatrix}17&18&11\\18&29&4\\11&4&13\end{pmatrix}$
  
__б)__  
  
### $\begin{pmatrix}4&5&2\\1&-2&3\end{pmatrix}\cdot\begin{pmatrix}4&1\\5&-2\\2&3\end{pmatrix}=\begin{pmatrix}4\cdot4+5\cdot5+2\cdot2&4\cdot1+5\cdot(-2)+2\cdot3\\1\cdot4+(-2)\cdot5+3\cdot2&1\cdot1+(-2)\cdot(-2)+3\cdot3\end{pmatrix}=\begin{pmatrix}45&0\\0&14\end{pmatrix}$

In [4]:
A = np.array([
    [4, 1],
    [5, -2],
    [2, 3]
])
AT = A.T
print(np.dot(A, AT))
print(np.dot(AT, A))

[[17 18 11]
 [18 29  4]
 [11  4 13]]
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [5]:
from pprint import pprint

def matrix_dot(a: list, b: list):
    result = []
    # здесь вставить код на проверку, что матрицы можно перемножить, и если можно, тогда код ниже
    lenth_a = len(a)
    lenth_b = len(b)
    for k in range(lenth_a):
        lst = []
        for i in range(lenth_b):
            sums = 0
            for j in range(lenth_b):
                sums = sums + a[k][j]*b[j][i]
            lst.append(sums)
        result.append(lst)
    return result


In [6]:
a = [
    [1, 2, 3],
    [3, 4, 5]
]
b = [
    [7, 8, 9],
    [6, 5, 4],
    [3, 2, 1]
]

pprint(matrix_dot(a, b))

[[28, 24, 20], [60, 54, 48]]


In [7]:
np.dot(a, b)

array([[28, 24, 20],
       [60, 54, 48]])

__Часть 2__

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$




__Решние:__  
__а)__  
### $det\begin{vmatrix}sinx & -cosx\\cosx & sinx\end{vmatrix}=\sin x\cdot\sin x - (-\cos x)\cdot\cos x = \sin^{2}x+\cos^{2}x=1$  
__б)__   
### $det\begin{vmatrix}4 & 2 & 3\\0 & 5 & 1\\0 & 0 & 9\end{vmatrix}=4\cdot5\cdot9=180$  
__в)__  
### $det\begin{vmatrix}1 & 2 & 3\\ 4 & 5 & 6\\ 7 & 8 & 9\end{vmatrix}=1\cdot\begin{vmatrix}5&6\\8&9\end{vmatrix}-2\cdot\begin{vmatrix}4&6\\7&9\end{vmatrix}+3\begin{vmatrix}4&5\\7&9\end{vmatrix}=(5\cdot9-6\cdot8)-2(4\cdot9-6\cdot7)+3(4\cdot8-5\cdot7)=0$

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   


__Решение:__  
__а)__  
### $det(A^2)=det(A\cdot A)=detA\cdot detA=4\cdot4=16$  
__б)__  
### $det(A^{T})=detA=4$  
__в)__  
### $det(2A)=2^{n}\cdot4$

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.


__Решение:__  
Первая и вторая строки представленной матрицы линейно зависимы, вторая строка - это первая строка умноженная на -2, значит определитель этой матрицы равен нулю, следовательно представленная матрица является вырожденной

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

__Решение:__  
__а)__  
Третья строка - это сумма первой и второй, значит её можно удалить, также поменяем первую и вторрую местами получим  
### $\begin{vmatrix}1&1&1\\1&2&3\end{vmatrix}$  
Теперь вычтем из второй строки первую умноженную на один, получим
### $\begin{vmatrix}1&1&1\\0&1&2\end{vmatrix}$ $\Rightarrow \text{ ранг матрицы равен 2}$  
__б)__  
Третья строка - это сумма первой и второй, значит её можно удалить, четвертую строку меняем местамаи с первой  
### $\begin{vmatrix}2&3&5&6\\0&0&2&1\\0&0&2&2\end{vmatrix} \Rightarrow \text{ ранг матрицы равен 3}$  

In [8]:
A = np.array([
    [1, 2, 3],
    [1, 1, 1],
    [2, 3, 4]
])
B = np.array([
    [0, 0, 2, 1],
    [0, 0, 2, 2],
    [0, 0, 4, 3],
    [2, 3, 5, 6]
])

print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(B))

2
3
