# Линейная алгебра
# GeekBrains
## ДЗ Урока 4
## Виталий Казанцев

1. Найдите посредством NumPy SVD для матрицы:

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [1]:
import numpy as np

In [2]:
A = np.array([
    [1,2,3],
    [0,0,5],
    [3,-4,2],
    [1,6,5],
    [0,1,0]
])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  3]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [3]:
U, s, W = np.linalg.svd(A)
V = W.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [10]:
print(f'Матрица D:\n{D[:2]}')

Матрица D:
[[9.43164369 0.         0.        ]
 [0.         6.11245421 0.        ]]


In [5]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.38829992 -0.10757267 -0.18204399 -0.88468356 -0.14780488]
 [ 0.39997989 -0.46021529  0.7809217   0.04975445  0.12611018]
 [-0.0824348  -0.85485592 -0.48296     0.15524149  0.07124313]
 [ 0.82323696  0.17891694 -0.33226026  0.41895909 -0.0659245 ]
 [ 0.06873627  0.11764393 -0.11564624 -0.12342148  0.97612925]]


In [6]:
print(f'Матрица V:\n{V}')

Матрица V:
[[ 0.10223377 -0.40789238 -0.9072883 ]
 [ 0.64829602  0.71909314 -0.25023454]
 [ 0.75449356 -0.56260898  0.33795061]]


In [7]:
print(np.dot(np.dot(U, D), V.T))

[[ 1.00000000e+00  2.00000000e+00  3.00000000e+00]
 [ 2.22044605e-16  3.33066907e-16  5.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00  2.00000000e+00]
 [ 1.00000000e+00  6.00000000e+00  5.00000000e+00]
 [-2.77555756e-17  1.00000000e+00  3.05311332e-16]]


2. Для матрицы из предыдущего задания найдите:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [8]:
print(f'Евклидова норма для заданной матрицы равна {max(s):.2f}')

Евклидова норма для заданной матрицы равна 9.43


In [9]:
print(f'Норма Фробениуса для заданной матрицы равна {np.sqrt(sum(s**2)):.2f}')

Норма Фробениуса для заданной матрицы равна 11.45
